---
title: ""
format: html
page-layout: full
---
<div>
<center><h1>Guía de Estudio</h1></center>
<p>En esta sección encontrarás material de apoyo (apuntes de estudiantes) para el estudio de los temas de la asignatura de Aprendizaje y Conducta Adaptable con el Dr. Arturo Bouzas.</p>
</div>

<div>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 20px;
            transition: background-color 0.3s, color 0.3s;
        }
        /* Estilo del encabezado de la tabla */
        th {
            background: linear-gradient(135deg, rgba(0, 123, 255, 0.2), rgba(0, 123, 255, 0.1));
            color: #007BFF;
            text-transform: uppercase;
            font-size: 14px;
            font-weight: bold;
            padding: 10px;
            border-bottom: 2px solid rgba(0, 123, 255, 0.5);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 8px;
            text-align: center;
            border: 1px solid #ddd;
        }
        tbody tr:nth-child(odd) {
            background-color: rgba(0, 0, 0, 0.05); /* Sutilmente visible en cualquier fondo */
        }
        .author-name {
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            color: #007BFF;
            margin-bottom: 10px;
            padding: 10px;
            background: linear-gradient(to right, rgba(0, 123, 255, 0.2), rgba(123, 255, 234, 0.2));
            border-radius: 10px;
        }
        iframe {
            width: 100%;
            height: 800px;
            border: none;
            margin-top: 20px;
        }
        .tag {
            display: inline-block;
            padding: 5px 10px;
            border: 1px solid #007BFF;
            border-radius: 15px;
            color: #007BFF;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <!-- Visor embebido de PDF -->
    <h2>Guía de Estudio para Aprendizaje y Conducta Adaptativa 2</h2>
    <div class="author-name">Por María Nore Rodríguez González</div>
    <iframe src="guides/notes_aca_2.pdf" title="Visor de PDF"></iframe> 
</body>
</div>